sqs:
  image: s12v/elasticmq
  ports:
    - "9324:9324"
    - "4789:9324"
sns:
  image: wellcome/fake-sns
  ports:
    - "9292:9292"
s3:
  image: "zenko/cloudserver:8.1.8"
  environment:
    - "S3BACKEND=mem"
  ports:
    - "33333:8000"
dynamodb:
  image: "peopleperhour/dynamodb"
  ports:
    - "45678:8000"
